"""add_association_table

Revision ID: 410eef3e94c7
Revises: 1f34c7dfb930
Create Date: 2023-06-04 14:39:42.928362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410eef3e94c7'
down_revision = '1f34c7dfb930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_actor_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actor_association')
    # ### end Alembic commands ###
